version: "3"
services:
  strapi:
    container_name: strapi
    build: ./strapi/
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_ROOT_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    image: docker.io/bitnami/mariadb:latest
    restart: unless-stopped
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "mariadb_data:/bitnami/mariadb"
      - "./bd:/docker-entrypoint-initdb.d"
    networks:
      - strapi

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_ROOT_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_ALLOW_NO_PASSWORD: false
      PHPMYADMIN_ALLOW_ARBITRARY_SERVER: yes
    ports:
      - "88:8080"
    networks:
      - strapi
    depends_on:
      - strapiDB

  nginx:
    image: "bitnami/nginx:latest"
    restart: unless-stopped
    depends_on:
      - strapi
    networks:
      - strapi
    links:
      - strapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/yourapp.conf:cached
      - ./frontend/:/srv/www/html/

volumes:
  mariadb_data:
    driver: local

networks:
  strapi:
    name: Strapi
    driver: bridge
